mv Anna_Tekken_5.jpg             anna_williams.jpg     
mv Asuka_Tekken_5.jpg            asuka_kazama.jpg     
mv Baek_Tekken_5.jpg             baek_doo_san.jpg     
mv BRUCE_TK5.jpg                 bruce_irvin.jpg      
mv Bryan_Fury_Tekken_5.jpg       bryan_fury.jpg       
mv Christie_TK5.jpg              christie_monteiro.jpg
mv Craig_Marduk_Tekken_5.jpg     craig_marduk.jpg     
mv DEVIL_JIN_TK5.jpg             devil_jin.jpg        
mv EDDY_TK5.jpg                  eddy_gordo.jpg       
mv FENG_TK5.jpg                  feng_wei.jpg         
mv Ganryu_Tekken_5.jpg           ganryu.jpg           
mv HeihachiTK5.jpg               heihachi_mishima.jpg 
mv Hwoarang_Tekken_5.jpg         hwoarang.jpg         
mv Jack_TK5.jpg                  jack-5.jpg           
mv Jin_Kazama_Tekken_5.jpg       jin_kazama.jpg       
mv Julia_Tekken_5.jpg            julia_chang.jpg                         
mv Kazuya_Tekken_5.jpg           kazuya_mishima.jpg                      
mv King_Tekken_5.jpg             king_ii.jpg                             
mv Kuma_TK5.jpg                  kuma.jpg                                
mv Lee_Tekken_5.jpg              lee_chaolan.jpg                         
mv Lei_TK5.jpg                   lei_wulong.jpg                          
mv Xiaoyu_Tekken_5.jpg           ling_xiaoyu.jpg                         
mv Marshall_Law_TK5.jpg          marshall_law.jpg                        
mv Nina_Williams_Tekken_5.jpg    nina_williams.jpg                       
mv Paul_Phoenix_TK5.jpg          paul_phoenix.jpg  
mv Raven_TK5.jpg                 raven.jpg         
mv ROGER_JR_TK5.jpg              roger_jr..jpg     
mv Steve_Fox_TK5.jpg             steve_fox.jpg     
mv WANG_TK5.jpg                  wang_jinrei.jpg   
mv Yoshimitsu_Tekken_5.jpg       yoshimitsu.jpg    
